version: 2
updates:
  - package-ecosystem: "maven"     # or npm, gradle, etc.
    directory: "/"                 # where pom.xml is located
    schedule:
      interval: "weekly"           # daily | weekly | monthly
    open-pull-requests-limit: 5    # optional limit
